// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vizpzrphgbvipqskgjrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpenB6cnBoZ2J2aXBxc2tnanJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTgwNDIsImV4cCI6MjA2MzAzNDA0Mn0.b936lQYnBOkEfnk0uNXztGyECZ9vGcQ9E_3OR9RtYQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);